// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Menu struct {
	ID           int32
	ParentID     pgtype.Int4
	Label        string
	Icon         pgtype.Text
	Path         pgtype.Text
	SortOrder    int32
	PermissionID pgtype.Int4
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Permission struct {
	ID          int32
	Code        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Role struct {
	ID          int32
	Name        string
	Description pgtype.Text
	IsActive    bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type RolePermission struct {
	RoleID       int32
	PermissionID int32
}

type User struct {
	ID           pgtype.UUID
	Email        string
	Username     string
	PasswordHash string
	Name         string
	IsSuperadmin bool
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type UserRole struct {
	UserID     pgtype.UUID
	RoleID     int32
	AssignedAt pgtype.Timestamptz
}
