// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, username, password_hash, name)
VALUES ($1, $2, $3, $4)
RETURNING id, email, username, name, is_superadmin, is_active
`

type CreateUserParams struct {
	Email        string
	Username     string
	PasswordHash string
	Name         string
}

type CreateUserRow struct {
	ID           pgtype.UUID
	Email        string
	Username     string
	Name         string
	IsSuperadmin bool
	IsActive     bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.Name,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.IsSuperadmin,
		&i.IsActive,
	)
	return i, err
}
