package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"

	"github.com/AgungRilo/kolamku/backend/graph/model"
	"github.com/AgungRilo/kolamku/backend/internal/db/sqlcgen"
	"golang.org/x/crypto/bcrypt"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.User, error) {
	// 1. Hash password mentah dari user. JANGAN pernah simpan password asli.
	hashed, err := bcrypt.GenerateFromPassword([]byte(input.Password), bcrypt.DefaultCost)
	if err != nil {
		return nil, fmt.Errorf("gagal hash password: %w", err)
	}

	// 2. Insert user baru lewat sqlc.
	queries := sqlcgen.New(r.DB)
	row, err := queries.CreateUser(ctx, sqlcgen.CreateUserParams{
		Email:        input.Email,
		Username:     input.Username,
		PasswordHash: string(hashed),
		Name:         input.Name,
	})
	if err != nil {
		return nil, fmt.Errorf("gagal membuat user: %w", err)
	}

	// 3. Map hasil DB -> model GraphQL.
	return &model.User{
		ID:           row.ID.String(),
		Email:        row.Email,
		Username:     row.Username,
		Name:         row.Name,
		IsSuperadmin: row.IsSuperadmin,
		IsActive:     row.IsActive,
	}, nil
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}

// Roles is the resolver for the roles field.
func (r *queryResolver) Roles(ctx context.Context) ([]*model.Role, error) {
	// 1. Bikin query object sqlc, kasih pool DB dari resolver.
	queries := sqlcgen.New(r.DB)

	// 2. Panggil query SQL ListRoles (baca dari tabel roles).
	rows, err := queries.ListRoles(ctx)
	if err != nil {
		return nil, err
	}

	// 3. Terjemahkan hasil sqlc -> model GraphQL (dua tipe Role yang beda).
	var result []*model.Role
	for _, row := range rows {
		role := &model.Role{
			ID:   row.ID,
			Name: row.Name,
		}
		// description nullable: cuma isi kalau ada nilainya (Valid = true).
		if row.Description.Valid {
			desc := row.Description.String
			role.Description = &desc
		}
		result = append(result, role)
	}

	return result, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
